In [1]:
print('hello')

hello


In [3]:
import numpy as np

print(np.__version__)

2.5.2


In [4]:
import torch

In [5]:
print(torch.__version__)

2.13.0+cpu


In [6]:
print(torch.cuda.is_available())

False


PyTorch에서 GPU 가속 사용 가능 여부를 확인하고 장치(Device)를 지정

In [7]:
import torch
import torch.nn as nn

# 1. 실행 환경에 맞는 장치(Device) 동적 할당 (표준 패턴)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("현재 사용 장치:", device)

# 2. 텐서 생성 시 처음부터 지정된 장치로 할당 (메모리 이동 오버헤드 방지)
x = torch.ones((2, 3), device=device)

# 3. 기존 텐서를 지정 장치로 이동
# Note: 텐서의 .to()는 원본을 변경하지 않고 '새로운 텐서'를 반환합니다.
y = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
y = y.to(device)

# 4. 신경망 모델을 지정 장치로 이동
# Note: 모델의 .to()는 모델 내부 파라미터를 'In-place(제자리)'로 이동시킵니다.
model = nn.Linear(2, 2).to(device)

# 5. 모델 연산 실행
output = model(y)
print("출력 결과 장치:", output.device)

현재 사용 장치: cpu
출력 결과 장치: cpu


# 데이터로부터 직접 생성

In [14]:
a = torch.tensor([[1,2], [3,4]])
print(a)

# python 리스트로부터 생성
list_data = [[1,2,3],[4,5,6]]
print(f'list_data: {list_data}')
type(list_data)
tensor_from_list = torch.tensor(list_data, dtype=torch.float32)
print(f'List -> tensor: {tensor_from_list}')
print(type(tensor_from_list.dtype))   #<class 'torch.Tensor'>

tensor([[1, 2],
        [3, 4]])
list_data: [[1, 2, 3], [4, 5, 6]]
List -> tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])
<class 'torch.dtype'>


In [ ]:
np_array = np.array([10,20,30])
tensor_from_np = torch.from_numpy(np_array)   #torch.tensor랑 다르다
print(f'tensor_from_np: {tensor_from_np}')

tensor_from_np[0] = 999
print(f'np_array: {np_array}')
print(f'tensor_from_np: {tensor_from_np}')

np_array[0] = 500
print(f'np_array: {np_array}')
print(f'tensor_from_np: {tensor_from_np}')


tensor_from_np: tensor([10, 20, 30])
np_array: [999  20  30]
tensor_from_np: tensor([999,  20,  30])
np_array: [500  20  30]
tensor_from_np: tensor([500,  20,  30])


##### 1.2 특정 형태(Shape)와 값으로 초기화 (Structured Initialization)

In [28]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
np.full((3,2),3)

array([[3, 3],
       [3, 3],
       [3, 3]])

In [ ]:
shape = (2, 3)
print(f'zeros: {torch.zeros(shape)}')
print(f'ones: {torch.ones(shape)}')
print(f'empty: {torch.empty(shape)}')
print(f'full: {torch.full(shape,3)}')


# 범위 기반 생성
# arange의 핵심은 “일자로 배열한다”가 아니라 “일정한 간격으로 숫자를 생성한다”.
print(f'arange: {torch.arange(10)}')
print(f'arange: {torch.arange(0, 10)}')
print(f'arange: {torch.arange(0, 10, 2)}')

print(f'linspace: {torch.linspace(1, 10, 5)}')  
# linspace는 시작값부터 끝값까지 일정한 간격으로 숫자를 원하는 개수만큼 만들어주는 함수

np.linspace(1, 10, 5)

zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones: tensor([[1., 1., 1.],
        [1., 1., 1.]])
empty: tensor([[0., 0., 0.],
        [0., 0., 0.]])
full: tensor([[3, 3, 3],
        [3, 3, 3]])
arange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])


##### 1.3. 무작위 난수로 초기화 (Random Initialization)

In [42]:
torch.manual_seed(42)   # torch.manual_seed(42)는 난수 생성 결과를 고정하는 코드

print(f'rand: {torch.rand(2,2)}')   # *size
print(f'rand: {torch.rand((2,2,3))}')

print(f'rand: {torch.rand(2,2)}')
print(f'randint: {torch.randint(10, (2,2))}')
print(f'randint: {torch.randint(1, 10, (2,2))}')

print(f'randperm: {torch.randperm(10)}') # 0부터 n-1까지만의 정수를 무작위로 섞인 `차 텐서 생성`

rand: tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
rand: tensor([[[0.3904, 0.6009, 0.2566],
         [0.7936, 0.9408, 0.1332]],

        [[0.9346, 0.5936, 0.8694],
         [0.5677, 0.7411, 0.4294]]])
rand: tensor([[0.8854, 0.5739],
        [0.2666, 0.6274]])
randint: tensor([[9, 6],
        [3, 1]])
randint: tensor([[9, 5],
        [3, 1]])
randperm: tensor([7, 2, 6, 8, 5, 9, 0, 3, 4, 1])


##### 1.4. 기존 텐서의 속성을 복사하여 초기화 (_like 계열)

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(f'x: {x}')

# shpae와 dtype을 그대로 복사해온다.
x_zeros = torch.zeros_like(x)
print(f'zeros_like: {torch.zeros_like(x)}')

x_ones = torch.ones_like(x)
print(f'zeros_like: {x_zeros}, dtype:{x_zeros.dtype}')

x_rand = torch.rand_like(x)
print(f'rand_like: {x_rand}, dtype:{x_rand.dtype}')

# x의 타입이 float32이므로 그 타입을 그대로 따라서 사용이 된다.(주의)
x_randint = torch.randint_like(x, 10)
print(f'randint_like:{x_randint}, dtype:{x_randint.dtype}')



x: tensor([[1., 2., 3.],
        [4., 5., 6.]])
zeros_like: tensor([[0., 0., 0.],
        [0., 0., 0.]])
zeros_like: tensor([[0., 0., 0.],
        [0., 0., 0.]]), dtype:torch.float32
rand_like: tensor([[0.3336, 0.5782, 0.0600],
        [0.2846, 0.2007, 0.5014]]), dtype:torch.float32
randint_like:tensor([[6., 7., 6.],
        [0., 9., 5.]]), dtype:(torch.float32, <class 'int'>)


##### 1.5. 텐서의 주요 속성 (Attributes)

In [59]:
# 속성을 명시하며 텐서 생성

tensor_attr = torch.ones((2, 3), dtype=torch.float16, device="cpu")

print("Shape (차원):", tensor_attr.shape)
print("Datatype (타입):", tensor_attr.dtype)
print("Device (장치):", tensor_attr.device)

# 타입 변경 및 디바이스 이동
tensor_float32 = tensor_attr.to(dtype=torch.float32)
print("변경된 Datatype:", tensor_float32.dtype)

# GPU가 사용 가능한 경우 CUDA 장치로 이동
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("이동된 Device:", device )

Shape (차원): torch.Size([2, 3])
Datatype (타입): torch.float16
Device (장치): cpu
변경된 Datatype: torch.float32
이동된 Device: cpu


### 2. 텐서 사이즈

##### 2.1 크기 및 차원 확인 (Size Inspection)

In [63]:
np.shape(x)
np.ndim(x)

2

In [74]:
x = torch.arange(24).reshape(2,3,4) # (2,3,4) 크기의 3차원 텐서
print(f'x: {x}')

print(f'shape: {x.shape}')  # torch.size([2,3,4])
print(f'ndim: {x.ndim}')  # 3size 차원
print(f'size: {x.size(0)}')  # 2번 축의 길이가 4라는 뜻이다 1번축은 따라서 3이다.
print(f'numel: {x.numel()}')  # 24: 텐서 내부의 전체 요소의 개수



x: tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
shape: torch.Size([2, 3, 4])
ndim: 3
size: 2
numel: 24


##### 크기변경 및 형상 조작

In [ ]:
x = torch.arange(24).reshape(2,3,4) # (2,3,4) 크기의 3차원 텐서

# view()
x_view = x.view(2, 12)   # 2차원 행렬로 바꿔준것이다. 
x_auto = x.reshape(-1, 6)  # 열은 6개로 고정하고 알아서 행렬을 만들어 달라는 뜻이다.
print(x_auto)


tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])


In [83]:
import torch

# 1. 텐서 생성 및 기본 크기 확인
x = torch.arange(24).reshape(2, 3, 4) # (2, 3, 4) 크기의 3차원 텐서

print("Shape:", x.shape)            # torch.Size([2, 3, 4])
print("Rank (차원 수):", x.ndim)    # 3
print("Total Elements:", x.numel()) # 24
print("1번 차원 크기:", x.size(1))  # 3

# 2. view와 reshape
x_view = x.view(2, 12)             # (2, 12)로 변경
x_auto = x.reshape(-1, 6)          # (4, 6)으로 자동 계산
 
# squeeze는 크기가 1인 차원만 제거하는 함수야.
# 3. unsqueeze & squeeze
x_2d = torch.randn(3, 4)            # Shape: (3, 4)
x_unsqueeze = x_2d.unsqueeze(0)    # Shape: (1, 3, 4) - 배치 차원 추가 시 활용 // 0으로 설정하면 batch 차원 추가함
x_squeeze = x_unsqueezed.squeeze() # Shape: (3, 4)    np.newaxis

# unsqueeze(axis): 축을 추가할 때 사용한다.
x_squeeze = x_unsqueeze.squeeze(0)    # 0으로 설정하면 batch 차원 추가함
print(f'x_unsqueeze : {x_squeeze.shape}')   # torch.size([1,3,4])

# 차원 축소?
x_squeeze = x_unsqueeze.squeeze()    
print(f'x_unsqueeze : {x_squeeze.shape}')  # torch.size([3,4])


# 4. permute (차원 재배치)
img_tensor = torch.randn(32, 3, 224, 224) # (Batch, Channel, Height, Width)
img_permuted = img_tensor.permute(0, 2, 3, 1) # (Batch, Height, Width, Channel)
print("\nPermuted Shape:", img_permuted.shape) # torch.Size([32, 224, 224, 3])

# 5. expand vs repeat
a = torch.tensor([[1], [2]])       # Shape: (2, 1)

print(f'expand: {a.expand(2,4)}')
print(f'repeat: {a.repeat(1,4)}')

a_expanded = a.expand(2, 4)        # 메모리 복사 없이 (2, 4)로 확장
a_repeated = a.repeat(1, 4)        # 실제 데이터를 4번 복사하여 (2, 4) 생성

Shape: torch.Size([2, 3, 4])
Rank (차원 수): 3
Total Elements: 24
1번 차원 크기: 3
x_unsqueeze : torch.Size([3, 4])
x_unsqueeze : torch.Size([3, 4])

Permuted Shape: torch.Size([32, 224, 224, 3])
expand: tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]])
repeat: tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]])


In [85]:
import torch

# 3x4 크기의 2차원 텐서 생성
x = torch.tensor([[ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12]])

print("원본 텐서:\n", x)

# 1. 단일 요소 접근 (1행 2열 -> 값: 7)
print("\n1. 특정 위치 요소 (1, 2):", x[1, 2].item())

# 2. 특정 행/열 전체 추출
print("2-1. 첫 번째 행 전체 (0, :):", x[0, :])
print("2-2. 마지막 열 전체 (:, -1):", x[:, -1])

# 3. 범위 슬라이싱 (0~1행, 1~2열 추출)
# [start:end]에서 end는 포함되지 않음
print("3. 부분 텐서 추출:\n", x[0:2, 1:3])

# 4. 간격 지정 슬라이싱 (step=2)
print("4. 2칸 간격 추출:", x[:, ::2])

원본 텐서:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

1. 특정 위치 요소 (1, 2): 7
2-1. 첫 번째 행 전체 (0, :): tensor([1, 2, 3, 4])
2-2. 마지막 열 전체 (:, -1): tensor([ 4,  8, 12])
3. 부분 텐서 추출:
 tensor([[2, 3],
        [6, 7]])
4. 2칸 간격 추출: tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])


### 3.2 고급 인덱싱 (Advanced Indexing)

In [ ]:
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

# 1. 불리언 마스킹 (50보다 큰 요소만 추출)
mask = x > 50
print("마스크 (Boolean Tensor):\n", mask)
print("50보다 큰 값만 추출:", x[mask])  # 1차원 텐서로 반환됨

# 2. 인덱스 리스트를 활용한 추출 (팬시 인덱싱)
# 0행과 2행 추출
rows = torch.tensor([0, 2])
print("\n0행과 2행 추출:\n", x[rows])

# 3. torch.index_select 사용 (dim=1: 열 기준 추출)
cols = torch.tensor([0, 2]) # 0열과 2열 선택
selected_cols = torch.index_select(x, dim=1, index=cols)   # dim=1은 열축을 따라 가는 것이다. / 여기선 3행 3열이 되는 것이기 때문에 1번 축이 열이 된다.
print("0열과 2열 추출 (index_select):\n", selected_cols)

마스크 (Boolean Tensor):
 tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
50보다 큰 값만 추출: tensor([60, 70, 80, 90])

0행과 2행 추출:
 tensor([[10, 20, 30],
        [70, 80, 90]])
0열과 2열 추출 (index_select):
 tensor([[10, 30],
        [40, 60],
        [70, 90]])


### 3.3 텐서 결합 (Joining Tensors)

In [ ]:
t1 = torch.tensor([[1, 2],
                   [3, 4]])

t2 = torch.tensor([[5, 6],
                   [7, 8]])

# 1. torch.cat (기존 차원 이어붙이기)
# dim=0: 세로 방향(행)으로 붙임
cat_dim0 = torch.cat([t1, t2], dim=0)    # 지정한 차원대로 차원이 늘어나는 것이다.
print("torch.cat (dim=0) Shape:", cat_dim0.shape)   # cat은 모양이 달라도 성립이 된디.
print(cat_dim0)

# dim=1: 가로 방향(열)으로 붙임
cat_dim1 = torch.cat([t1, t2], dim=1)
print("\ntorch.cat (dim=1) Shape:", cat_dim1.shape)
print(cat_dim1)

# 2. torch.stack (새로운 차원 생성하며 쌓기)
# dim=0: 맨 앞에 새로운 차원 추가 (2, 2, 2)
stacked = torch.stack([t1, t2], dim=0)    # stack은 모양이 같아야만 성립이 된다.
print("\ntorch.stack (dim=0) Shape:", stacked.shape)
print(stacked)

torch.cat (dim=0) Shape: torch.Size([4, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

torch.cat (dim=1) Shape: torch.Size([2, 4])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

torch.stack (dim=0) Shape: torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


### 3.4 텐서 분할

In [ ]:
x = torch.arange(12).reshape(4, 3) # 4행 3열 텐서
print("분할할 원본 텐서 (4x3):\n", x)

# 1. torch.split: 행 방향(dim=0)으로 2행씩 분할
split_result = torch.split(x, split_size_or_sections=2, dim=0)
print("\nsplit (크기 3씩 분할 결과):")
for t in split_result:
    print(t)

# 두덩어리냐 몇개씩 잘라라의 차이다.

# 2. torch.chunk: 행 방향(dim=0)으로 총 2개의 덩어리로 분할
chunk_result = torch.chunk(x, chunks=2, dim=0)
print("\nchunk (2개로 등분 결과):")
for t in chunk_result:
    print(t)

분할할 원본 텐서 (4x3):
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

split (크기 3씩 분할 결과):
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

chunk (2개로 등분 결과):
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])


In [92]:
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
float_tensor = torch.tensor([0.5, 1.5, 2.5], dtype=torch.float32)

# int32 + float32 -> float32로 자동 승격
result = int_tensor + float_tensor
print("연산 결과:", result)
print("자동 승격된 dtype:", result.dtype) # torch.float32

연산 결과: tensor([1.5000, 3.5000, 5.5000])
자동 승격된 dtype: torch.float32


### 집계함수

In [93]:
x = torch.tensor([[1.0, 5.0, 3.0],
                  [4.0, 2.0, 6.0]]) # Shape: (2, 3)

# 1. 전체 요소 집계
print("전체 합:", x.sum().item())
print("전체 평균:", x.mean().item())

# 2. 차원(dim) 기준 집계
# dim=0: 행 방향(세로)으로 뭉쳐서 연산 -> 결과 Shape: (3,)
print("\n열 기준(dim=0) 평균:", x.mean(dim=0))

# dim=1: 열 방향(가로)으로 뭉쳐서 연산 -> 결과 Shape: (2,)
print("행 기준(dim=1) 최댓값:", x.max(dim=1).values)

# 3. keepdim=True 옵션
sum_keepdim = x.sum(dim=1, keepdim=True)
print("\nkeepdim=True 적용 합 Shape:", sum_keepdim.shape) # (2, 1)

# 4. Argmax (최댓값의 인덱스 위치)
print("\n행 기준 가장 큰 값의 인덱스 (dim=1):", x.argmax(dim=1)) # [1, 2]

전체 합: 21.0
전체 평균: 3.5

열 기준(dim=0) 평균: tensor([2.5000, 3.5000, 4.5000])
행 기준(dim=1) 최댓값: tensor([5., 6.])

keepdim=True 적용 합 Shape: torch.Size([2, 1])

행 기준 가장 큰 값의 인덱스 (dim=1): tensor([1, 2])


### 6.4 제자리 연산 (In-place Operations)

In [94]:
x = torch.tensor([1.0, 2.0, 3.0])
print("초기 메모리 주소:", id(x))

# Out-of-place 연산 (새로운 텐서 생성 -> 주소 변경됨)
x_new = x + 5.0
print("Out-of-place 후 x 주소:", id(x))

# In-place 연산 (기존 텐서 메모리에 즉시 반영 -> 주소 동일)
x.add_(5.0)
print("In-place 연산 후 x 값:", x)
print("In-place 후 x 주소:", id(x)) # 초기 주소와 동일함

# 모든 요소를 0으로 초기화
x.zero_()
print("zero_() 적용 후:", x)

초기 메모리 주소: 2317783647968
Out-of-place 후 x 주소: 2317783647968
In-place 연산 후 x 값: tensor([6., 7., 8.])
In-place 후 x 주소: 2317783647968
zero_() 적용 후: tensor([0., 0., 0.])
